columnSuffix: utogshfz
contentColumnType: text
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
